# Generated by Django 4.0.3 on 2022-03-13 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='edited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
