# Generated by Django 4.0.3 on 2022-03-13 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0002_layer_edited_alter_layer_text_alter_layer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layer',
            name='layers',
            field=models.ManyToManyField(to='croissant.layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='participants',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
