# Generated by Django 4.0.3 on 2022-03-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0003_layer_creator_layer_layers_layer_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
