# Generated by Django 4.0.3 on 2022-03-14 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0005_alter_layer_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='layers',
        ),
        migrations.AddField(
            model_name='layer',
            name='children',
            field=models.ManyToManyField(blank=True, to='croissant.layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='end_date',
            field=models.DateField(blank=True, default='2022-02-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='end_time',
            field=models.TimeField(blank=True, default='22:29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layer',
            name='start_date',
            field=models.DateField(blank=True, default='2022-02-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='start_time',
            field=models.TimeField(blank=True, default='22:29'),
            preserve_default=False,
        ),
    ]
