# Generated by Django 4.0.3 on 2022-03-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0007_alter_layer_description_alter_layer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='end_date',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='end_time',
            field=models.TimeField(blank=True, default='99:99'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='start_date',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='start_time',
            field=models.TimeField(blank=True, default='99:99'),
        ),
    ]
