# Generated by Django 4.0.3 on 2022-03-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0009_alter_layer_children_alter_layer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='end_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='end_time',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layer',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layer',
            name='start_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='start_time',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
