# Generated by Django 4.0.3 on 2022-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0010_alter_layer_description_alter_layer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='children',
            field=models.ManyToManyField(blank=True, default='', to='croissant.layer'),
        ),
    ]
