# Generated by Django 4.0.3 on 2022-03-20 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0014_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='9999-99-99')),
                ('time', models.TimeField(blank=True, default='99:99')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='9999-99-99')),
                ('time', models.TimeField(blank=True, default='99:99')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='start',
            name='layer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='croissant.layer'),
        ),
        migrations.AddField(
            model_name='end',
            name='layer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='croissant.layer'),
        ),
    ]
