# Generated by Django 4.0.3 on 2022-03-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0015_end_start_alter_layer_owner_delete_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start',
            name='layer_id',
        ),
        migrations.DeleteModel(
            name='End',
        ),
        migrations.DeleteModel(
            name='Start',
        ),
    ]
