# Generated by Django 4.0.3 on 2022-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0016_remove_start_layer_id_delete_end_delete_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='layer',
            name='owner',
        ),
        migrations.AddField(
            model_name='layer',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
