# Generated by Django 4.0.3 on 2022-03-20 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0017_alter_layer_options_remove_layer_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='participants',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layer',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layer',
            name='tasks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
