# Generated by Django 4.0.3 on 2022-03-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0019_layer_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amound', models.PositiveIntegerField(default=1)),
                ('layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='croissant.layer')),
            ],
        ),
    ]
