# Generated by Django 4.0.3 on 2022-03-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0020_remove_layer_tasks_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='amound',
            new_name='amount',
        ),
    ]
