# Generated by Django 4.0.3 on 2022-03-21 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0022_tasks_created_alter_layer_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='layer',
            name='children',
        ),
        migrations.AddField(
            model_name='layer',
            name='tasks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='child',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='croissant.layer'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='croissant.layer'),
        ),
    ]
