# Generated by Django 4.0.3 on 2022-03-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0023_child_remove_layer_children_layer_tasks_delete_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='children',
            field=models.ManyToManyField(blank=True, to='croissant.layer'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
