# Generated by Django 4.0.3 on 2022-03-21 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croissant', '0024_layer_children_delete_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='layer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='layer',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
