# Generated by Django 4.0.3 on 2022-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0027_start_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='children',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='participants',
        ),
    ]
