# Generated by Django 4.0.3 on 2022-03-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0029_rename_date_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='start',
            name='using_time',
        ),
        migrations.AddField(
            model_name='start',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='start',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
