# Generated by Django 4.0.3 on 2022-03-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0030_remove_start_datetime_remove_start_using_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='layer_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='croissant.layer'),
        ),
    ]
