# Generated by Django 4.0.3 on 2022-03-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0031_alter_start_layer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start',
            old_name='layer_id',
            new_name='layer',
        ),
    ]
