# Generated by Django 4.0.3 on 2022-03-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0035_alter_layer_options_remove_layer_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-07 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
