# Generated by Django 4.0.3 on 2022-03-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0037_alter_start_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='layer',
            field=models.ForeignKey(db_constraint=False, default=18, on_delete=django.db.models.deletion.DO_NOTHING, related_name='start', to='croissant.layer'),
            preserve_default=False,
        ),
    ]
