# Generated by Django 4.0.3 on 2022-03-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0038_alter_start_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='child',
            field=models.ForeignKey(blank=True, default='17', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='croissant.layer'),
            preserve_default=False,
        ),
    ]
