# Generated by Django 4.0.3 on 2022-03-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0039_layer_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='child',
        ),
        migrations.AddField(
            model_name='layer',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='croissant.layer'),
        ),
    ]
