# Generated by Django 4.0.3 on 2022-03-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0040_remove_layer_child_layer_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='children',
        ),
        migrations.AddField(
            model_name='layer',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='croissant.layer'),
        ),
    ]
