# Generated by Django 4.0.3 on 2022-04-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0041_remove_layer_children_layer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='layer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starts', to='croissant.layer'),
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ends', to='croissant.layer')),
            ],
        ),
    ]
