# Generated by Django 4.0.3 on 2022-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissant', '0042_alter_start_layer_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='layer',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
